//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CodeProjectAngular.WebAPI
{
    using System;
    using System.Collections.Generic;
    
    public partial class Book
    {
        public string TITLE { get; set; }
        public string CATNUM { get; set; }
        public string COMPOSERS1 { get; set; }
        public string PUBLISHER { get; set; }
        public string TITLEYEAR { get; set; }
        public string SUBJECT { get; set; }
        public string KEYWORDS { get; set; }
        public string NOTES1 { get; set; }
        public string NOTES2 { get; set; }
        public string COMPOSERS2 { get; set; }
        public string COMPOSERS3 { get; set; }
        public string COMPOSERS4 { get; set; }
        public int ID_BOOKS { get; set; }
        public Nullable<bool> PRINT { get; set; }
        public Nullable<bool> NewRec { get; set; }
        public Nullable<int> TOTAL_ROWS { get; set; }
        public string SORT_BY { get; set; }
        public string SEARCHBOX { get; set; }
        public Nullable<int> ROW_NUM { get; set; }
    }
}
