//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CodeProjectAngular.WebAPI
{
    using System;
    using System.Collections.Generic;
    
    public partial class C78
    {
        public string TITLE { get; set; }
        public string CATNUM { get; set; }
        public string COMPOSERS1 { get; set; }
        public string PUBLISHER { get; set; }
        public string COMPOSERS2 { get; set; }
        public string COMPOSERS3 { get; set; }
        public string COMPOSERS4 { get; set; }
        public string PRODTYPE { get; set; }
        public string PRODTITLE { get; set; }
        public string ARRANGTYPE { get; set; }
        public string NOTES1 { get; set; }
        public string NOTES2 { get; set; }
        public Nullable<int> id_transfer { get; set; }
        public Nullable<bool> PRINT { get; set; }
        public Nullable<bool> NewRec { get; set; }
        public string PERFORMERS1 { get; set; }
        public string LYRICISTS1 { get; set; }
        public string COMPANY { get; set; }
        public string PERFORMERS2 { get; set; }
        public string LYRICISTS2 { get; set; }
        public string LYRICISTS3 { get; set; }
        public string LYRICISTS4 { get; set; }
        public int ID_78 { get; set; }
        public string PERFORMERS3 { get; set; }
        public string PERFORMERS4 { get; set; }
        public string DONE { get; set; }
        public string MATRIX { get; set; }
        public string MATRIX_NUM { get; set; }
        public string MATRIX_PREFIX { get; set; }
        public string MATRIX_SUFFIX { get; set; }
        public string LOCATION { get; set; }
        public string PAGE_LINK { get; set; }
        public string RecDay { get; set; }
        public string RecMonth { get; set; }
        public string RecYear { get; set; }
        public string FLD1 { get; set; }
        public string FLD2 { get; set; }
        public string FLD3 { get; set; }
        public string FLD4 { get; set; }
        public string FLD5 { get; set; }
        public string FLD6 { get; set; }
        public string FLD7 { get; set; }
        public string FLD8 { get; set; }
        public string FLD1_DATA { get; set; }
        public string FLD2_DATA { get; set; }
        public string FLD3_DATA { get; set; }
        public string FLD4_DATA { get; set; }
        public string FLD5_DATA { get; set; }
        public string FLD6_DATA { get; set; }
        public string FLD7_DATA { get; set; }
        public string FLD8_DATA { get; set; }
        public Nullable<int> FLD_2_COUNT { get; set; }
        public Nullable<int> FLD_3_COUNT { get; set; }
        public string YEAR_SHEETMUS { get; set; }
        public string UCASE_FLD2_DATA { get; set; }
        public Nullable<int> TOTAL_ROWS { get; set; }
        public string SORT_BY { get; set; }
        public string PICTURE { get; set; }
        public string SEARCHBOX { get; set; }
        public Nullable<int> ROW_NUM { get; set; }
        public string YOUTUBE { get; set; }
    }
}
