//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CodeProjectAngular.WebAPI
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class CatalogDbEntities : DbContext
    {
        public CatalogDbEntities()
            : base("name=CatalogDbEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Orchestration> Orchestrations { get; set; }
        public virtual DbSet<SheetMus> SheetMus { get; set; }
        public virtual DbSet<C78> C78 { get; set; }
        public virtual DbSet<Book> Books { get; set; }
        public virtual DbSet<FilmSongPerson> FilmSongPersons { get; set; }
        public virtual DbSet<Pianorol> Pianorols { get; set; }
        public virtual DbSet<Prp> Prps { get; set; }
        public virtual DbSet<Silent> Silents { get; set; }
        public virtual DbSet<Solo> Solos { get; set; }
        public virtual DbSet<Track> Tracks { get; set; }
    }
}
