//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CodeProjectAngular.WebAPI
{
    using System;
    using System.Collections.Generic;
    
    public partial class FilmSongPerson
    {
        public string FilmTitle { get; set; }
        public Nullable<int> FilmYear { get; set; }
        public string SongTitle { get; set; }
        public string Person { get; set; }
        public string Role { get; set; }
        public int ID_FILMSONGPERSON { get; set; }
        public Nullable<int> TOTAL_ROWS { get; set; }
        public string SORT_BY { get; set; }
        public string PICTURE { get; set; }
    }
}
