//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CodeProjectAngular.WebAPI
{
    using System;
    using System.Collections.Generic;
    
    public partial class SheetMus
    {
        public string TITLE { get; set; }
        public string CATNUM { get; set; }
        public string COMPOSERS1 { get; set; }
        public string LYRICISTS1 { get; set; }
        public string PUBLISHER { get; set; }
        public string COMPOSERS2 { get; set; }
        public string COMPOSERS3 { get; set; }
        public string COMPOSERS4 { get; set; }
        public string LYRICISTS2 { get; set; }
        public string LYRICISTS3 { get; set; }
        public string LYRICISTS4 { get; set; }
        public string PHOTO1 { get; set; }
        public string PHOTO2 { get; set; }
        public string PHOTO3 { get; set; }
        public string PHOTO4 { get; set; }
        public string PRODTYPE { get; set; }
        public string PRODTITLE { get; set; }
        public string ARRANGTYPE { get; set; }
        public string NOTES1 { get; set; }
        public string NOTES2 { get; set; }
        public string PLATE_NUMBER { get; set; }
        public string KEY { get; set; }
        public int ID_SHEETMUS { get; set; }
        public Nullable<int> id_transfer { get; set; }
        public Nullable<bool> PRINT { get; set; }
        public Nullable<bool> LARGE { get; set; }
        public Nullable<bool> NewRec { get; set; }
        public string ARRANGYEAR { get; set; }
        public string PCN { get; set; }
        public Nullable<int> TOTAL_ROWS { get; set; }
        public string SORT_BY { get; set; }
    }
}
