//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CodeProjectAngular.WebAPI
{
    using System;
    using System.Collections.Generic;
    
    public partial class Track
    {
        public string TITLE { get; set; }
        public string MEDIA_TITLE { get; set; }
        public string MEDIACAT { get; set; }
        public string MEDIUM { get; set; }
        public Nullable<bool> PRINT { get; set; }
        public string CATNUM { get; set; }
        public string TITLEYEAR { get; set; }
        public string COMPOSERS1 { get; set; }
        public string COMPOSERS2 { get; set; }
        public string COMPOSERS3 { get; set; }
        public string COMPOSERS4 { get; set; }
        public string PERFORMERS1 { get; set; }
        public string PERFORMERS2 { get; set; }
        public string PERFORMERS3 { get; set; }
        public string PERFORMERS4 { get; set; }
        public string PUBLISHER { get; set; }
        public string ARRANGERS1 { get; set; }
        public string ARRANGERS2 { get; set; }
        public string LYRICISTS1 { get; set; }
        public string LYRICISTS2 { get; set; }
        public string LYRICISTS3 { get; set; }
        public string LYRICISTS4 { get; set; }
        public Nullable<bool> NewRec { get; set; }
        public string NOTES1 { get; set; }
        public string NOTES2 { get; set; }
        public string sourcetable { get; set; }
        public Nullable<int> sourcetableid { get; set; }
        public Nullable<bool> bLinkedToSourceTable { get; set; }
        public string ARRANGYEAR { get; set; }
        public string ARRANGTYPE { get; set; }
        public string COMPANY { get; set; }
        public Nullable<int> RECORD_DAY { get; set; }
        public Nullable<int> RECORD_MONTH { get; set; }
        public Nullable<int> RECORD_YEAR { get; set; }
        public string PRODTYPE { get; set; }
        public string PRODTITLE { get; set; }
        public string SOURCE_COMPANY { get; set; }
        public int ID_TRACKS { get; set; }
        public Nullable<int> ID_MEDIA { get; set; }
        public Nullable<int> TOTAL_ROWS { get; set; }
        public string SORT_BY { get; set; }
        public string PICTURE { get; set; }
    }
}
